name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Debug SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
          echo "Connecting to server..."
          cd /var/www/html/ecommerce-app  # Ubah direktori ke /var/www/html/ecommerce-app
          git pull origin main
          pm2 restart ecommerce-app --update-env
          echo "Deployment finished"
        EOF
